### ISSUE TITLE
[bug] - Música não é adiciona na playlist do spotify quando música de uma playlist do youtube está tocando

### ISSUE THREAD

**Issue by eliezer-of** [andrevictor06/pcmr-bot-discord#114]
quando é adicionado um link de uma playlist, a música que está tocando não é adicionada na playlist no spotify

ex: https://www.youtube.com/watch?v=pm-xlwkQ_qc&list=RDEMRqoQL64rv6SjrtGBi5sbDQ&index=27

**Comment by jonasgsouza** [comment]
Corrigido #115
